// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class KeyResult {
    /**
     * Creates a new KeyResult instance.
     * @param {Partial<KeyResult>} [$$source = {}] - The source object to create the KeyResult.
     */
    constructor($$source = {}) {
        if (!("licenseKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["licenseKey"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyResult(/** @type {Partial<KeyResult>} */($$parsedSource));
    }
}

export class SaveResult {
    /**
     * Creates a new SaveResult instance.
     * @param {Partial<SaveResult>} [$$source = {}] - The source object to create the SaveResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("licenseKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["licenseKey"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult(/** @type {Partial<SaveResult>} */($$parsedSource));
    }
}
