// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export class CommandMeta {
    /**
     * Creates a new CommandMeta instance.
     * @param {Partial<CommandMeta>} [$$source = {}] - The source object to create the CommandMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cwd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandMeta}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        return new CommandMeta(/** @type {Partial<CommandMeta>} */($$parsedSource));
    }
}

export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("sourceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceType"] = "";
        }
        if (!("projectRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectRoot"] = "";
        }
        if (!("phpSapi" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phpSapi"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["requestId"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HTTPMeta | null | undefined}
             */
            this["http"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CommandMeta | null | undefined}
             */
            this["command"] = undefined;
        }
        if (!("isDd" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDd"] = false;
        }
        if (!("payloadFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payloadFormat"] = "";
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {json$0.RawMessage}
             */
            this["payload"] = null;
        }
        if (!("trace" in $$source)) {
            /**
             * @member
             * @type {TraceFrame[]}
             */
            this["trace"] = [];
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {HostMeta}
             */
            this["host"] = (new HostMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("http" in $$parsedSource) {
            $$parsedSource["http"] = $$createField7_0($$parsedSource["http"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField8_0($$parsedSource["command"]);
        }
        if ("trace" in $$parsedSource) {
            $$parsedSource["trace"] = $$createField12_0($$parsedSource["trace"]);
        }
        if ("host" in $$parsedSource) {
            $$parsedSource["host"] = $$createField13_0($$parsedSource["host"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

export class HTTPMeta {
    /**
     * Creates a new HTTPMeta instance.
     * @param {Partial<HTTPMeta>} [$$source = {}] - The source object to create the HTTPMeta.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("scheme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scheme"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["query"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["statusCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["clientIp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["userAgent"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPMeta(/** @type {Partial<HTTPMeta>} */($$parsedSource));
    }
}

export class HostMeta {
    /**
     * Creates a new HostMeta instance.
     * @param {Partial<HostMeta>} [$$source = {}] - The source object to create the HostMeta.
     */
    constructor($$source = {}) {
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostMeta(/** @type {Partial<HostMeta>} */($$parsedSource));
    }
}

export class TraceFrame {
    /**
     * Creates a new TraceFrame instance.
     * @param {Partial<TraceFrame>} [$$source = {}] - The source object to create the TraceFrame.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["file"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["line"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["func"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceFrame instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TraceFrame}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraceFrame(/** @type {Partial<TraceFrame>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = HTTPMeta.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = CommandMeta.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = TraceFrame.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = HostMeta.createFrom;
