// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionResult {
    /**
     * Creates a new ActionResult instance.
     * @param {Partial<ActionResult>} [$$source = {}] - The source object to create the ActionResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("requiresPrivilege" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresPrivilege"] = false;
        }
        if (!("suggestedCommands" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["suggestedCommands"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("suggestedCommands" in $$parsedSource) {
            $$parsedSource["suggestedCommands"] = $$createField5_0($$parsedSource["suggestedCommands"]);
        }
        return new ActionResult(/** @type {Partial<ActionResult>} */($$parsedSource));
    }
}

export class Extension {
    /**
     * Creates a new Extension instance.
     * @param {Partial<Extension>} [$$source = {}] - The source object to create the Extension.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("iniPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iniPath"] = "";
        }
        if (!("iniExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["iniExists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Extension}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Extension(/** @type {Partial<Extension>} */($$parsedSource));
    }
}

export class ExtensionToggleRequest {
    /**
     * Creates a new ExtensionToggleRequest instance.
     * @param {Partial<ExtensionToggleRequest>} [$$source = {}] - The source object to create the ExtensionToggleRequest.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionToggleRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtensionToggleRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionToggleRequest(/** @type {Partial<ExtensionToggleRequest>} */($$parsedSource));
    }
}

export class IniSettings {
    /**
     * Creates a new IniSettings instance.
     * @param {Partial<IniSettings>} [$$source = {}] - The source object to create the IniSettings.
     */
    constructor($$source = {}) {
        if (!("uploadMaxFilesize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploadMaxFilesize"] = "";
        }
        if (!("postMaxSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postMaxSize"] = "";
        }
        if (!("memoryLimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["memoryLimit"] = "";
        }
        if (!("maxExecutionTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maxExecutionTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IniSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IniSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IniSettings(/** @type {Partial<IniSettings>} */($$parsedSource));
    }
}

export class IniSettingsUpdateRequest {
    /**
     * Creates a new IniSettingsUpdateRequest instance.
     * @param {Partial<IniSettingsUpdateRequest>} [$$source = {}] - The source object to create the IniSettingsUpdateRequest.
     */
    constructor($$source = {}) {
        if (!("uploadMaxFilesize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uploadMaxFilesize"] = "";
        }
        if (!("postMaxSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postMaxSize"] = "";
        }
        if (!("memoryLimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["memoryLimit"] = "";
        }
        if (!("maxExecutionTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maxExecutionTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IniSettingsUpdateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IniSettingsUpdateRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IniSettingsUpdateRequest(/** @type {Partial<IniSettingsUpdateRequest>} */($$parsedSource));
    }
}

export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("activeVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeVersion"] = "";
        }
        if (!("versions" in $$source)) {
            /**
             * @member
             * @type {Version[]}
             */
            this["versions"] = [];
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {IniSettings}
             */
            this["settings"] = (new IniSettings());
        }
        if (!("extensions" in $$source)) {
            /**
             * @member
             * @type {Extension[]}
             */
            this["extensions"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField4_0($$parsedSource["versions"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField6_0($$parsedSource["extensions"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

export class Version {
    /**
     * Creates a new Version instance.
     * @param {Partial<Version>} [$$source = {}] - The source object to create the Version.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Version}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version(/** @type {Partial<Version>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Version.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = IniSettings.createFrom;
const $$createType4 = Extension.createFrom;
const $$createType5 = $Create.Array($$createType4);
