// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dump$0 from "./internal/dump/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as setup$0 from "./internal/setup/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyValetLinuxRemediation(confirm: boolean): $CancellablePromise<setup$0.ValetLinuxRemediationResult> {
    return $Call.ByID(886757788, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DecodeDumpEventNDJSONLine(line: string): $CancellablePromise<dump$0.Event | null> {
    return $Call.ByID(3383830637, line).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DumpEventChannelName(): $CancellablePromise<string> {
    return $Call.ByID(1234117607);
}

export function EnableCLIHook(): $CancellablePromise<setup$0.HookInstallResult> {
    return $Call.ByID(3101749583).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetCollectorStatus(): $CancellablePromise<$models.CollectorStatus> {
    return $Call.ByID(3825867284).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetRecentEvents(limit: number): $CancellablePromise<dump$0.Event[]> {
    return $Call.ByID(607076933, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSetupDiagnostics(): $CancellablePromise<setup$0.Diagnostics> {
    return $Call.ByID(222824292).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetValetLinuxVerification(): $CancellablePromise<setup$0.ValetLinuxVerification> {
    return $Call.ByID(1888362080).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

export function SupportedDumpEventSchemaVersion(): $CancellablePromise<number> {
    return $Call.ByID(640390982);
}

// Private type creation functions
const $$createType0 = setup$0.ValetLinuxRemediationResult.createFrom;
const $$createType1 = dump$0.Event.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = setup$0.HookInstallResult.createFrom;
const $$createType4 = $models.CollectorStatus.createFrom;
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = setup$0.Diagnostics.createFrom;
const $$createType7 = setup$0.ValetLinuxVerification.createFrom;
