// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dump$0 from "../dump/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} line
 * @returns {$CancellablePromise<dump$0.Event | null>}
 */
export function DecodeDumpEventNDJSONLine(line) {
    return $Call.ByID(2282382060, line).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DumpEventChannelName() {
    return $Call.ByID(2064947480);
}

/**
 * @returns {$CancellablePromise<$models.CollectorStatus>}
 */
export function GetCollectorStatus() {
    return $Call.ByID(678154095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<dump$0.Event[]>}
 */
export function GetRecentEvents(limit) {
    return $Call.ByID(599144652, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function SupportedDumpEventSchemaVersion() {
    return $Call.ByID(392301343);
}

// Private type creation functions
const $$createType0 = dump$0.Event.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CollectorStatus.createFrom;
const $$createType3 = $Create.Array($$createType0);
