// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as license$0 from "../domain/license/models.js";

/**
 * @returns {$CancellablePromise<license$0.KeyResult>}
 */
export function GetLicenseKey() {
    return $Call.ByID(2466226825).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} licenseKey
 * @returns {$CancellablePromise<license$0.SaveResult>}
 */
export function SaveLicenseKey(licenseKey) {
    return $Call.ByID(3005883014, licenseKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = license$0.KeyResult.createFrom;
const $$createType1 = license$0.SaveResult.createFrom;
