// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CollectorStatus {
    /**
     * Creates a new CollectorStatus instance.
     * @param {Partial<CollectorStatus>} [$$source = {}] - The source object to create the CollectorStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("socketPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["socketPath"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("dropped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dropped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectorStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CollectorStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectorStatus(/** @type {Partial<CollectorStatus>} */($$parsedSource));
    }
}
