// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as phpmanager$0 from "../domain/phpmanager/models.js";

/**
 * @returns {$CancellablePromise<phpmanager$0.Snapshot>}
 */
export function GetPHPManagerSnapshot() {
    return $Call.ByID(498487661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<phpmanager$0.ActionResult>}
 */
export function InstallPHPVersion(version) {
    return $Call.ByID(687587217, version).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {phpmanager$0.ExtensionToggleRequest} request
 * @returns {$CancellablePromise<phpmanager$0.ActionResult>}
 */
export function SetPHPExtensionState(request) {
    return $Call.ByID(2213040700, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<phpmanager$0.ActionResult>}
 */
export function SwitchPHPVersion(version) {
    return $Call.ByID(586753686, version).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {phpmanager$0.IniSettingsUpdateRequest} request
 * @returns {$CancellablePromise<phpmanager$0.ActionResult>}
 */
export function UpdatePHPIniSettings(request) {
    return $Call.ByID(254775976, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = phpmanager$0.Snapshot.createFrom;
const $$createType1 = phpmanager$0.ActionResult.createFrom;
