// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as setup$0 from "../setup/models.js";

/**
 * @param {boolean} confirm
 * @returns {$CancellablePromise<setup$0.ValetLinuxRemediationResult>}
 */
export function ApplyValetLinuxRemediation(confirm) {
    return $Call.ByID(3981884522, confirm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<setup$0.HookInstallResult>}
 */
export function EnableCLIHook() {
    return $Call.ByID(3486349685).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<setup$0.Diagnostics>}
 */
export function GetSetupDiagnostics() {
    return $Call.ByID(1874792066).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<setup$0.ValetLinuxVerification>}
 */
export function GetValetLinuxVerification() {
    return $Call.ByID(4123474282).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<setup$0.ValetSitesResult>}
 */
export function GetValetSites() {
    return $Call.ByID(3284235411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = setup$0.ValetLinuxRemediationResult.createFrom;
const $$createType1 = setup$0.HookInstallResult.createFrom;
const $$createType2 = setup$0.Diagnostics.createFrom;
const $$createType3 = setup$0.ValetLinuxVerification.createFrom;
const $$createType4 = setup$0.ValetSitesResult.createFrom;
