// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../domain/update/models.js";

/**
 * @param {string} manifestURL
 * @returns {$CancellablePromise<update$0.CheckResult>}
 */
export function CheckForUpdate(manifestURL) {
    return $Call.ByID(3757243367, manifestURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function CurrentVersion() {
    return $Call.ByID(4240081258);
}

/**
 * @param {string} manifestURL
 * @returns {$CancellablePromise<update$0.DownloadResult>}
 */
export function DownloadLatest(manifestURL) {
    return $Call.ByID(2707916054, manifestURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} downloadedPath
 * @returns {$CancellablePromise<update$0.InstallResult>}
 */
export function InstallDownloaded(downloadedPath) {
    return $Call.ByID(3146719909, downloadedPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = update$0.CheckResult.createFrom;
const $$createType1 = update$0.DownloadResult.createFrom;
const $$createType2 = update$0.InstallResult.createFrom;
