// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Diagnostics {
    /**
     * Creates a new Diagnostics instance.
     * @param {Partial<Diagnostics>} [$$source = {}] - The source object to create the Diagnostics.
     */
    constructor($$source = {}) {
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("phpFound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["phpFound"] = false;
        }
        if (!("phpVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phpVersion"] = "";
        }
        if (!("phpIniOutput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phpIniOutput"] = "";
        }
        if (!("serviceManager" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serviceManager"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostics(/** @type {Partial<Diagnostics>} */($$parsedSource));
    }
}

export class FPMServiceStatus {
    /**
     * Creates a new FPMServiceStatus instance.
     * @param {Partial<FPMServiceStatus>} [$$source = {}] - The source object to create the FPMServiceStatus.
     */
    constructor($$source = {}) {
        if (!("serviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serviceName"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("confDPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["confDPath"] = "";
        }
        if (!("hookIniPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hookIniPath"] = "";
        }
        if (!("hookIniExists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hookIniExists"] = false;
        }
        if (!("autoPrependFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["autoPrependFile"] = "";
        }
        if (!("matchesExpected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["matchesExpected"] = false;
        }
        if (!("systemdActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["systemdActive"] = false;
        }
        if (!("systemdEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["systemdEnabled"] = false;
        }
        if (!("restartCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["restartCommand"] = "";
        }
        if (!("verificationCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["verificationCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FPMServiceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FPMServiceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FPMServiceStatus(/** @type {Partial<FPMServiceStatus>} */($$parsedSource));
    }
}

export class HookInstallResult {
    /**
     * Creates a new HookInstallResult instance.
     * @param {Partial<HookInstallResult>} [$$source = {}] - The source object to create the HookInstallResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("alreadyEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alreadyEnabled"] = false;
        }
        if (!("phpIniPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phpIniPath"] = "";
        }
        if (!("prependPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prependPath"] = "";
        }
        if (!("backupPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupPath"] = "";
        }
        if (!("socketPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["socketPath"] = "";
        }
        if (!("requiresSudo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresSudo"] = false;
        }
        if (!("suggestedCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestedCmd"] = "";
        }
        if (!("privilegeStrategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["privilegeStrategy"] = "";
        }
        if (!("privilegeAttempted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["privilegeAttempted"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HookInstallResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HookInstallResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HookInstallResult(/** @type {Partial<HookInstallResult>} */($$parsedSource));
    }
}

export class ValetLinuxRemediationResult {
    /**
     * Creates a new ValetLinuxRemediationResult instance.
     * @param {Partial<ValetLinuxRemediationResult>} [$$source = {}] - The source object to create the ValetLinuxRemediationResult.
     */
    constructor($$source = {}) {
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("confirmed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmed"] = false;
        }
        if (!("applied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["applied"] = false;
        }
        if (!("expectedPrependPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expectedPrependPath"] = "";
        }
        if (!("requiresSudo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresSudo"] = false;
        }
        if (!("suggestedCommands" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["suggestedCommands"] = [];
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {ValetRemediationTarget[]}
             */
            this["targets"] = [];
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetLinuxRemediationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValetLinuxRemediationResult}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("suggestedCommands" in $$parsedSource) {
            $$parsedSource["suggestedCommands"] = $$createField6_0($$parsedSource["suggestedCommands"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField7_0($$parsedSource["targets"]);
        }
        return new ValetLinuxRemediationResult(/** @type {Partial<ValetLinuxRemediationResult>} */($$parsedSource));
    }
}

export class ValetLinuxVerification {
    /**
     * Creates a new ValetLinuxVerification instance.
     * @param {Partial<ValetLinuxVerification>} [$$source = {}] - The source object to create the ValetLinuxVerification.
     */
    constructor($$source = {}) {
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("valetDetected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valetDetected"] = false;
        }
        if (!("serviceManager" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serviceManager"] = "";
        }
        if (!("cliConfDPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cliConfDPath"] = "";
        }
        if (!("cliAutoPrepend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cliAutoPrepend"] = "";
        }
        if (!("expectedPrependPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expectedPrependPath"] = "";
        }
        if (!("fpmServices" in $$source)) {
            /**
             * @member
             * @type {FPMServiceStatus[]}
             */
            this["fpmServices"] = [];
        }
        if (!("recommendations" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["recommendations"] = [];
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetLinuxVerification instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValetLinuxVerification}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fpmServices" in $$parsedSource) {
            $$parsedSource["fpmServices"] = $$createField7_0($$parsedSource["fpmServices"]);
        }
        if ("recommendations" in $$parsedSource) {
            $$parsedSource["recommendations"] = $$createField8_0($$parsedSource["recommendations"]);
        }
        return new ValetLinuxVerification(/** @type {Partial<ValetLinuxVerification>} */($$parsedSource));
    }
}

export class ValetRemediationTarget {
    /**
     * Creates a new ValetRemediationTarget instance.
     * @param {Partial<ValetRemediationTarget>} [$$source = {}] - The source object to create the ValetRemediationTarget.
     */
    constructor($$source = {}) {
        if (!("serviceName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serviceName"] = "";
        }
        if (!("hookIniPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hookIniPath"] = "";
        }
        if (!("writeAttempted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["writeAttempted"] = false;
        }
        if (!("written" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["written"] = false;
        }
        if (!("writeError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["writeError"] = "";
        }
        if (!("restartAttempted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restartAttempted"] = false;
        }
        if (!("restarted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restarted"] = false;
        }
        if (!("restartError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["restartError"] = "";
        }
        if (!("restartCommand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["restartCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetRemediationTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValetRemediationTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValetRemediationTarget(/** @type {Partial<ValetRemediationTarget>} */($$parsedSource));
    }
}

export class ValetSite {
    /**
     * Creates a new ValetSite instance.
     * @param {Partial<ValetSite>} [$$source = {}] - The source object to create the ValetSite.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("isSecure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSecure"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phpVersion"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetSite instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValetSite}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValetSite(/** @type {Partial<ValetSite>} */($$parsedSource));
    }
}

export class ValetSitesResult {
    /**
     * Creates a new ValetSitesResult instance.
     * @param {Partial<ValetSitesResult>} [$$source = {}] - The source object to create the ValetSitesResult.
     */
    constructor($$source = {}) {
        if (!("generatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("sites" in $$source)) {
            /**
             * @member
             * @type {ValetSite[]}
             */
            this["sites"] = [];
        }
        if (!("parkedDirectories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["parkedDirectories"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetSitesResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValetSitesResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sites" in $$parsedSource) {
            $$parsedSource["sites"] = $$createField4_0($$parsedSource["sites"]);
        }
        if ("parkedDirectories" in $$parsedSource) {
            $$parsedSource["parkedDirectories"] = $$createField5_0($$parsedSource["parkedDirectories"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField6_0($$parsedSource["warnings"]);
        }
        return new ValetSitesResult(/** @type {Partial<ValetSitesResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ValetRemediationTarget.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FPMServiceStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ValetSite.createFrom;
const $$createType6 = $Create.Array($$createType5);
