// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setup} from '../models';
import {dump} from '../models';
import {main} from '../models';

export function ApplyValetLinuxRemediation(arg1:boolean):Promise<setup.ValetLinuxRemediationResult>;

export function DecodeDumpEventNDJSONLine(arg1:string):Promise<dump.Event>;

export function DumpEventChannelName():Promise<string>;

export function EnableCLIHook():Promise<setup.HookInstallResult>;

export function GetCollectorStatus():Promise<main.CollectorStatus>;

export function GetRecentEvents(arg1:number):Promise<Array<dump.Event>>;

export function GetSetupDiagnostics():Promise<setup.Diagnostics>;

export function GetValetLinuxVerification():Promise<setup.ValetLinuxVerification>;

export function Greet(arg1:string):Promise<string>;

export function SupportedDumpEventSchemaVersion():Promise<number>;
